[Variables]
; HWiNFO variables
; See https://forum.rainmeter.net/viewtopic.php?f=118&t=21939 for help with this

TempUnit=°C 

HWiNFODesc1=CPU Fan
HWiNFOSensorId1=0xf0ec0101
HWiNFOSensorInstance1=0x0
HWiNFOEntryId1=0x3000000
HWiNFOType1=CurrentValue
HWiNFOMin1=0
HWiNFOMax1=3449

HWiNFODesc2=CPU Chip
HWiNFOSensorId2=0xf0000400
HWiNFOSensorInstance2=0x0
HWiNFOEntryId2=0x1000000
HWiNFOType2=CurrentValue
HWiNFOMin2=15
HWiNFOMax2=90

HWiNFODesc3=Graphics
HWiNFOSensorId3=0xe0002000
HWiNFOSensorInstance3=0x14
HWiNFOEntryId3=0x1000000
HWiNFOType3=CurrentValue
HWiNFOMin3=25
HWiNFOMax3=90
